Redux saga
fcodelabs/training-web pull request #119
Opened 2021-12-14 15:03 UTC by Thushan97

[ ITP - 198 ] - Add the new cards to the firebase database and get cards from firebase database.

2021-12-15 15:50 UTC, Thushan97 commented
conflicts are resoleved.

2021-12-16 09:21 UTC, Thushan97 commented
conflicts are resolved.

2021-12-20 00:05 UTC, JinapriyaM requested changes

2021-12-20 00:05 UTC, JinapriyaM commented on src/Actions/AddCards.js
> +    await addDoc(collection(db, "posts"), card);
Only define relevant action here. Move this to a new saga.

2022-01-20 15:35 UTC, closed without merging