redux added, folder structure changed
fcodelabs/training-web pull request #244
Opened 2023-01-10 01:39 UTC by YumeChaan

[ITP-1156]
[ITP-1186]

2023-01-17 03:27 UTC, udara-sinister requested changes

2023-01-17 03:27 UTC, udara-sinister commented on src/App.tsx
> +    <Routes>
Use a separate route file to handle routings

2023-01-17 03:27 UTC, udara-sinister commented on src/utils/firebaseConfig.ts
> +const firebaseConfig = {
Use a separate .env file to store the sensitive data

2023-01-19 07:04 UTC, YumeChaan commented
Issues resolved in https://github.com/fcodelabs/training-web/pull/253

2023-01-31 04:44 UTC, closed without merging