ITP-1758
fcodelabs/training-web pull request #257
Opened 2023-07-06 07:55 UTC by exagenio

@shamal-iroshan 
@udara-sinister

2023-07-06 11:34 UTC, udaraJ08 approved these changes

2023-07-06 11:34 UTC, udaraJ08 commented on src/containers/Signin/Signin.tsx
> +    console.log("changed");
Remove unnecessary console.logs

2023-07-06 11:34 UTC, udaraJ08 commented on src/containers/Signin/Signin.tsx
> +    window.location.href = "/home";
Use React router do not use window location based routings

2023-07-06 14:41 UTC, shamal-iroshan commented on src/containers/Signin/Signin.tsx
> +  const randomNameGenerate = () => {
let's maintain a different file to handle these types of utility functions. create a folder name utils and move this function to that file

2023-07-06 14:43 UTC, shamal-iroshan commented on src/containers/Signin/Signin.tsx
> +    setNickname(randomNameGenerate);// Set a random name
is this working?

2023-07-06 14:43 UTC, shamal-iroshan requested changes
fix the commented things

2023-07-06 15:00 UTC, exagenio commented on src/containers/Signin/Signin.tsx
> +    setNickname(randomNameGenerate);// Set a random name
Yes it's working

2023-07-06 15:15 UTC, exagenio commented
@shamal-iroshan made the changes

2023-07-07 05:46 UTC, shamal-iroshan approved these changes

2023-07-07 05:47 UTC, merged