Abdullah
fcodelabs/training-web pull request #271
Opened 2023-07-07 16:12 UTC by AbdullahMarikkar

ITP-1759

2023-07-10 07:07 UTC, udaraJ08 approved these changes

2023-07-10 07:11 UTC, udaraJ08 requested changes

2023-07-10 07:11 UTC, udaraJ08 commented on dear-diary-react/src/components/DiaryForm.tsx
> +    console.log(cardInputs);
Remove unnecessary console.logs()

2023-07-10 07:11 UTC, udaraJ08 commented on dear-diary-react/src/components/DiaryForm.tsx
> +const cardInputs: any[] = [];
Do not use any. Define a custom data type using an interface

2023-07-11 04:01 UTC, shamal-iroshan commented on dear-diary-react/src/Containers/SignInFiles/SignIn.tsx
> +    <div
don't need to write components like this, use mui components and there way of styling

2023-07-11 04:02 UTC, shamal-iroshan commented on dear-diary-react/src/Containers/SignInFiles/SignIn.tsx
> +          <h1
here as well, change this also to a MUI component

2023-07-11 04:03 UTC, shamal-iroshan commented on dear-diary-react/src/components/AppRouter.tsx
> +        <Route path="/DiaryHome" element={<DiaryHome />} />
you can use constants to store these paths and use it when ever you want

2023-07-11 04:04 UTC, shamal-iroshan commented on dear-diary-react/src/components/Buttons/RandomButton.tsx
> +export const generateRandomName = function () {
move this random name generation function to a utility file

2023-07-11 04:05 UTC, shamal-iroshan commented on dear-diary-react/src/components/DiaryComponents/DiaryForm.tsx
> +// let inputValueOne = "";
if not needed remove these commented lines

2023-07-11 04:05 UTC, shamal-iroshan commented on dear-diary-react/src/components/DiaryComponents/DiaryForm.tsx
> +        {/* {showCard &&
if not needed remove these commented lines

2023-07-11 04:06 UTC, shamal-iroshan commented on dear-diary-react/src/components/DiaryComponents/DiaryForm.tsx
> +export function RecipeReviewCard(props: Cards) {
if this is a component move it to the components section

2023-07-11 04:06 UTC, shamal-iroshan requested changes
fix commented things

2023-07-17 01:33 UTC, merged