Created Sign-in page.
fcodelabs/training-web pull request #288
Opened 2023-08-29 02:02 UTC by TDimuth

2023-08-29 05:31 UTC, shamal-iroshan commented on dear-diary/src/containers/SignInPage/SignInCard.tsx
> +        navigate('/Diary');
better to store these routes as a constants and use that constant to navigate

2023-08-29 05:31 UTC, shamal-iroshan commented on dear-diary/src/containers/SignInPage/SignInCard.tsx
> +    const createRandomName = () => {
can move these kind of functions to util file

2023-08-29 05:34 UTC, shamal-iroshan requested changes
fix commented things,
When managing folder structure move components to a separate directory
ex:- SignInCard.tsx file should move to components/SignInCard/SignInCard.tsx

2023-08-29 07:47 UTC, TDimuth commented
Fixed commented issues

2023-08-31 14:33 UTC, shamal-iroshan approved these changes

2023-08-31 14:33 UTC, merged