Implement UIs and Adding Function
fcodelabs/training-web pull request #291
Opened 2023-09-26 08:57 UTC by Sandun-Induranga

[ITP-2265]  [ITP-2268]  [ITP-2274]  [ITP-2280]  [ITP-2289]  [ITP-2283]

2023-09-26 14:19 UTC, shamal-iroshan commented on src/components/DiaryCard/DiaryCard.tsx
> +        {props.description.length > 5 ? (
if you only need to render one component use && operator

2023-09-26 14:19 UTC, shamal-iroshan commented on src/containers/Context/Context.tsx
> +      <Route path="/home" element={<HomePage />} />
use a constant file to manage routes don't hardcode them everywhere

2023-09-26 14:21 UTC, shamal-iroshan commented on src/containers/Context/Context.tsx
> +import { Route, Routes } from "react-router-dom";
what is the meaning of this context file? only pages should be in the containers directory.

2023-09-26 14:22 UTC, shamal-iroshan commented on src/containers/HomePage/HomePage.tsx
> +          <></>
here also you can use && operator

2023-09-26 14:25 UTC, shamal-iroshan commented on src/types/DiaryCardProps.ts
> +export type DiaryCardProps = {
types that are needed for a page or component you can define them inside the component

2023-09-26 14:26 UTC, shamal-iroshan requested changes
fix commented things

2023-09-26 14:43 UTC, Sandun-Induranga commented on src/containers/Context/Context.tsx
> +import { Route, Routes } from "react-router-dom";
It is the Component that manage pages according to path

2023-10-02 04:12 UTC, shamal-iroshan approved these changes

2023-10-02 04:12 UTC, merged