Submit new diary card 1
fcodelabs/training-web pull request #292
Opened 2023-09-26 09:14 UTC by NimeshPiyumantha

[ITP-2266] [ITP-2269] [ITP-2275] [ITP-2278] [ITP-2290] [ITP-2284]

2023-09-26 14:28 UTC, shamal-iroshan commented on src/components/Content/Content.tsx
> +      <Route path="/" element={<SignInPage />} />
store routes in a constant file and use that, don't hardcode routes everywhere. and also rename this file as RootRouter or something.

2023-09-26 14:29 UTC, shamal-iroshan commented on src/components/DiaryCard/DiaryCard.tsx
> +interface DiaryCardProps {
better to start the name of an interface with I. ex:- IDiaryCardProps

2023-09-26 14:30 UTC, shamal-iroshan commented on src/components/DiaryCard/DiaryCard.tsx
> +  const cardStyle: React.CSSProperties = {
don't use inline styles or separate CSS files when using MUI, use there styled utility to create custom components or use there sx prop for adding styles

2023-09-26 14:32 UTC, shamal-iroshan commented on src/pages/DiaryHomePage/DiaryHome.tsx
> +      uName,
use meaningful names if this is a user name make it userName.

2023-09-26 14:33 UTC, shamal-iroshan commented on src/pages/DiaryHomePage/DiaryHome.tsx
> +    <ThemeProvider theme={theme}>
use theme provider and cssbaseline in root level not in component level

2023-09-26 14:33 UTC, shamal-iroshan commented on src/pages/SignInPage/SignInPage.tsx
> +  const generateRandomName = () => {
move this function into util directory

2023-09-26 14:34 UTC, shamal-iroshan commented on src/pages/SignInPage/SignInPage.tsx
> +    console.log(`Submitted name: ${name}`);
remove unwanted logs

2023-09-26 14:34 UTC, shamal-iroshan commented on src/pages/SignInPage/SignInPage.tsx
> +    <ThemeProvider theme={theme}>
fix this themeprovider and cssbaseline as well

2023-09-26 14:35 UTC, shamal-iroshan requested changes
fix commented things

2023-09-26 16:30 UTC, NimeshPiyumantha commented
Done

2023-10-02 04:13 UTC, shamal-iroshan approved these changes

2023-10-02 04:13 UTC, merged