Implement adding card 1
fcodelabs/training-web pull request #69
Opened 2021-08-20 10:52 UTC by lochanathiwanka

[ITP-128] Implement adding card 1

2021-08-21 12:00 UTC, Dulajdeshan commented on src/App.js
> +export const Context = React.createContext('');
Do not use context. Just try to use hooks and do these tasks.

2021-08-21 12:00 UTC, Dulajdeshan commented on src/components/DiaryCardContainer.js
> +                { context[0] !== undefined && context[2].map((data) => {
Use hooks to achieve these tasks instead of context.

2021-08-21 12:02 UTC, Dulajdeshan requested changes
Go through the comments and fix those

2021-08-23 03:52 UTC, JinapriyaM approved these changes

2021-08-24 14:44 UTC, Dulajdeshan approved these changes

2021-08-24 14:44 UTC, merged