Develop adding form
fcodelabs/training-web pull request #74
Opened 2021-08-21 22:51 UTC by jpbinith

2021-08-22 02:42 UTC, Dulajdeshan commented on src/components/add-form/add-form.js
> +                SHOW MORE
This should be Submit. Right?

2021-08-22 02:43 UTC, Dulajdeshan commented on src/components/diary-card/diary-card.js
> +                <Button className={classes.button} size="small" onClick={() => setIsMore(!isMore)}>SHOW MORE</Button>
Add SHOW LESS, to collapse the card.

2021-08-22 02:44 UTC, Dulajdeshan requested changes
Go through the comments

2021-08-22 08:00 UTC, JinapriyaM approved these changes

2021-08-24 14:38 UTC, Dulajdeshan approved these changes

2021-08-24 14:38 UTC, merged